In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("FData.xlsx")

In [3]:
df.head()

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4

In [4]:
df.shape

(61, 17)

In [5]:
df.columns

Index(['customer_id', 'first_name', 'gender', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     str
 2   gender              61 non-null     str
 3   age                 60 non-null     float64
 4   city                61 non-null     str
 5   province            61 non-null     str
 6   signup_date         61 non-null     str
 7   membership_tier     61 non-null     str
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     str
 13  device              61 non-null     str
 14  discount_used       61 non-null     str
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), str(9)
memory usage: 8.2 KB

In [7]:
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(1)

In [10]:
df[df.duplicated()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [11]:
df[df["customer_id"] == 1014]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [12]:
df = df.drop_duplicates()

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df[df['age'].isnull()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
19,1020,Kimia,M,NaN,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,Yes,1,5

In [15]:
df[df['total_spending'].isnull()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [16]:
df['age'].describe()

count     59.000000
mean      45.372881
std       19.284529
min       19.000000
25%       31.500000
50%       45.000000
75%       58.000000
max      145.000000
Name: age, dtype: float64

In [17]:
df[
    (df['gender'] == 'M') &
    (df['city'] == 'Isfahan') &
    (df['membership_tier'] == 'Bronze')
][['customer_id', 'first_name', 'age', 'membership_tier']]

    customer_id first_name  age membership_tier
19         1020      Kimia  NaN          Bronze

In [18]:
df['calculated_spending'] = (
    df['purchase_count'] * df['avg_order_value']
)

In [19]:
df[['purchase_count', 'avg_order_value', 'total_spending', 'calculated_spending']].head(10)

   purchase_count  avg_order_value  total_spending  calculated_spending
0              17           121.53         2066.01              2066.01
1              12           326.47         3917.64              3917.64
2              21            59.46         1248.66              1248.66
3              23           266.15         6121.45              6121.45
4              23           169.54         3899.42              3899.42
5              35           110.53         3868.55              3868.55
6              29            77.15         2237.35              2237.35
7               3           389.58         1168.74              1168.74
8              34           341.63        11615.42             11615.42
9              19           381.13         7241.47              7241.47

In [20]:
df['spending_difference'] = (
    df['total_spending'] - df['calculated_spending']
)

df['spending_difference'].describe()

count    5.900000e+01
mean     3.545908e+02
std      2.723664e+03
min     -1.818989e-12
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.092086e+04
Name: spending_difference, dtype: float64

In [21]:
df.loc[df['customer_id'] == 1020, 'age'] = 45

df.loc[df['customer_id'] == 1040, 'total_spending'] = (
    df.loc[df['customer_id'] == 1040, 'purchase_count'].iloc[0]
    * df.loc[df['customer_id'] == 1040, 'avg_order_value'].iloc[0]
)

In [22]:
df.drop(columns=['calculated_spending', 'spending_difference'], inplace=True)

In [23]:
df.isnull().sum()

customer_id           0
first_name            0
gender                0
age                   0
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        0
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [24]:
df.dtypes

customer_id             int64
first_name                str
gender                    str
age                   float64
city                      str
province                  str
signup_date               str
membership_tier           str
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method            str
device                    str
discount_used             str
returned_items          int64
satisfaction_score      int64
dtype: object

In [25]:
df.dtypes

customer_id             int64
first_name                str
gender                    str
age                   float64
city                      str
province                  str
signup_date               str
membership_tier           str
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method            str
device                    str
discount_used             str
returned_items          int64
satisfaction_score      int64
dtype: object

In [26]:
df['signup_date'].head(10)

0    2025-02-19
1    2022-08-19
2    2023-06-20
3    2021-11-08
4    2021-10-21
5    2022-01-26
6    2025-09-09
7    2024-10-03
8    2021-05-14
9    2022-06-25
Name: signup_date, dtype: str

In [27]:
df['signup_date'].tail(10)

50    2025-07-15
51    2022-03-18
52    2021-11-08
53    2021-03-26
54    2024-02-20
55    2025-01-25
56    2024-06-11
57    2024-09-27
58    2023-09-05
59    2021-04-27
Name: signup_date, dtype: str

In [28]:
df['signup_date'].unique()

<StringArray>
['2025-02-19', '2022-08-19', '2023-06-20', '2021-11-08', '2021-10-21',
 '2022-01-26', '2025-09-09', '2024-10-03', '2021-05-14', '2022-06-25',
 '2021-12-16', '2023-07-22', '2021-02-23', '2022-08-26', '2021-07-24',
 '2024-09-04', '2022-07-01', '2023-01-02', '2021-10-08', '2024-06-25',
 '2022-06-10', '2021-02-24', '2024-05-02', '2025-01-27', '2021-06-25',
 '2022-05-06', '2024-06-09', '2021-10-14', '2023-07-03', '2025-03-07',
 '2024-08-15', '2022-01-02', '2021-02-25', '2024-10-27', '2022-05-15',
 '2022-02-14', '2024-01-12', '2022-08-05', '2022-08-11', '2021-11-02',
 '2023-06-06', '2021-12-25', '2021-07-27', '2024-07-27', '2022-08-07',
 '2024-11-23', '2024-12-18', '2022-04-24', '2023-08-04', '2025-07-15',
 '2022-03-18', '2021-03-26', '2024-02-20', '2025-01-25', '2024-06-11',
 '2024-09-27', '2023-09-05', '2021-04-27']
Length: 58, dtype: str

In [29]:
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [30]:
df['signup_date'].dtype

dtype('<M8[us]')

In [31]:
df.dtypes

customer_id                    int64
first_name                       str
gender                           str
age                          float64
city                             str
province                         str
signup_date           datetime64[us]
membership_tier                  str
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method                   str
device                           str
discount_used                    str
returned_items                 int64
satisfaction_score             int64
dtype: object

In [32]:
df['age'] = df['age'].astype(int)

In [33]:
df[['age', 'signup_date']].head()

   age signup_date
0   19  2025-02-19
1   53  2022-08-19
2   31  2023-06-20
3   58  2021-11-08
4   28  2021-10-21

In [34]:
df[['age', 'signup_date']].dtypes

age                     int64
signup_date    datetime64[us]
dtype: object

In [35]:
df[df['age'] > 100]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [36]:
df['satisfaction_score'].value_counts().sort_index()

satisfaction_score
1    11
2    16
3     8
4    13
5    12
Name: count, dtype: int64

In [37]:
df['purchase_count'].describe()

count    60.000000
mean     17.383333
std      10.149880
min       0.000000
25%      10.750000
50%      17.000000
75%      24.500000
max      35.000000
Name: purchase_count, dtype: float64

In [ ]:
df['spending_difference'] = (
    df['total_spending'] - df['calculated_spending']
)

df['spending_difference'].describe()

count    5.900000e+01
mean     3.545908e+02
std      2.723664e+03
min     -1.818989e-12
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.092086e+04
Name: spending_difference, dtype: float64

In [38]:
df[df['purchase_count'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [39]:
df['returned_items'].describe()

count    60.000000
mean      4.183333
std       2.683861
min       0.000000
25%       2.000000
50%       4.000000
75%       7.000000
max       8.000000
Name: returned_items, dtype: float64

In [40]:
df[df['returned_items'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [41]:
df[df['returned_items'] > df['purchase_count']]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
7,1008,Reza,F,23,Rasht,Gilan,2024-10-03,VIP,3,389.58,1168.74,195,Online Wallet,iPhone,No,8,1
14,1015,Kimia,F,47,Ahvaz,Khuzestan,2021-07-24,Gold,3,307.91,923.73,55,Card,Android,Yes,8,4
23,1024,Sina,F,53,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.00,298,Online Wallet,Android,No,2,1
28,1029,Ali,F,34,Tabriz,East Azerbaijan,2023-07-03,Gold,2,323.32,646.64,319,Cash,Web,Yes,4,5
36,1037,Zahra,M,42,Ahvaz,Khuzestan,2024-01-12,Gold,1,387.68,387.68,199,Cash,Web,Yes,7,2
55,1056,Kimia,M,61,Tabriz,East Azerbaijan,2025-01-25,Silver,1,449.81,449.81,240,Online Wallet,Web,No,4,2

In [42]:
df['last_purchase_days'].describe()

count     60.000000
mean     198.600000
std       97.843043
min        3.000000
25%      134.250000
50%      203.000000
75%      273.750000
max      365.000000
Name: last_purchase_days, dtype: float64

In [43]:
df[df['last_purchase_days'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [44]:
df[df['avg_order_value'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [45]:
df[df['total_spending'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [46]:
for col in ['gender', 'city', 'province', 'membership_tier',
            'payment_method', 'device', 'discount_used']:
    print(f"\n--- {col} ---")
    print(df[col].unique())

--- gender ---
<StringArray>
['F', 'M']
Length: 2, dtype: str

--- city ---
<StringArray>
['Karaj', 'Tehran', 'Shiraz', 'Mashhad', 'Isfahan', 'Rasht', 'Tabriz',
 'Ahvaz']
Length: 8, dtype: str

--- province ---
<StringArray>
[         'Alborz',          'Tehran',            'Fars',        'Khorasan',
         'Isfahan',           'Gilan', 'East Azerbaijan',       'Khuzestan']
Length: 8, dtype: str

--- membership_tier ---
<StringArray>
['VIP', 'Gold', 'Silver', 'Bronze']
Length: 4, dtype: str

--- payment_method ---
<StringArray>
['Card', 'Online Wallet', 'Cash']
Length: 3, dtype: str

--- device ---
<StringArray>
['Android', 'Web', 'iPhone']
Length: 3, dtype: str

--- discount_used ---
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [47]:
df['payment_method'].value_counts()

payment_method
Online Wallet    23
Cash             19
Card             18
Name: count, dtype: int64

In [48]:
df['payment_method'].unique()

<StringArray>
['Card', 'Online Wallet', 'Cash']
Length: 3, dtype: str

In [49]:
df['device'].value_counts()

device
Android    22
Web        20
iPhone     18
Name: count, dtype: int64

In [50]:
df['device'].unique()

<StringArray>
['Android', 'Web', 'iPhone']
Length: 3, dtype: str

In [51]:
df[['city', 'province']].drop_duplicates().sort_values(['province', 'city'])

       city         province
0     Karaj           Alborz
13   Tabriz  East Azerbaijan
2    Shiraz             Fars
6     Rasht            Gilan
4   Isfahan          Isfahan
3   Mashhad         Khorasan
14    Ahvaz        Khuzestan
1    Tehran           Tehran

In [ ]:
df['device'].unique()

<StringArray>
['Android', 'Web', 'iPhone']
Length: 3, dtype: str

In [52]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"\n--- {col} ---")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")
    print(f"Number of outliers: {len(outliers)}")

NameError: name 'numeric_cols' is not defined

In [53]:
numeric_cols = [
    'age',
    'purchase_count',
    'avg_order_value',
    'total_spending',
    'last_purchase_days',
    'returned_items',
    'satisfaction_score'
]

In [54]:
for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    
    print(f"\n--- {col} ---")
    print(f"Q1: {Q1}")
    print(f"Q3: {Q3}")
    print(f"IQR: {IQR}")
    print(f"Lower Bound: {lower_bound}")
    print(f"Upper Bound: {upper_bound}")
    print(f"Number of outliers: {len(outliers)}")

--- age ---
Q1: 31.75
Q3: 58.0
IQR: 26.25
Lower Bound: -7.625
Upper Bound: 97.375
Number of outliers: 1

--- purchase_count ---
Q1: 10.75
Q3: 24.5
IQR: 13.75
Lower Bound: -9.875
Upper Bound: 45.125
Number of outliers: 0

--- avg_order_value ---
Q1: 108.1375
Q3: 324.1075
IQR: 215.97000000000003
Lower Bound: -215.81750000000005
Upper Bound: 648.0625
Number of outliers: 0

--- total_spending ---
Q1: 1167.035
Q3: 4692.15
IQR: 3525.115
Lower Bound: -4120.6375
Upper Bound: 9979.822499999998
Number of outliers: 5

--- last_purchase_days ---
Q1: 134.25
Q3: 273.75
IQR: 139.5
Lower Bound: -75.0
Upper Bound: 483.0
Number of outliers: 0

--- returned_items ---
Q1: 2.0
Q3: 7.0
IQR: 5.0
Lower Bound: -5.5
Upper Bound: 14.5
Number of outliers: 0

--- satisfaction_score ---
Q1: 2.0
Q3: 4.0
IQR: 2.0
Lower Bound: -1.0
Upper Bound: 7.0
Number of outliers: 0

In [55]:
outlier_summary = []

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    
    outlier_count = ((df[col] < lower_bound) | (df[col] > upper_bound)).sum()
    
    outlier_summary.append([
        col,
        Q1,
        Q3,
        IQR,
        lower_bound,
        upper_bound,
        outlier_count
    ])

outlier_summary_df = pd.DataFrame(
    outlier_summary,
    columns=[
        'column',
        'Q1',
        'Q3',
        'IQR',
        'lower_bound',
        'upper_bound',
        'outlier_count'
    ]
)

outlier_summary_df

,column,Q1,Q3,IQR,lower_bound,upper_bound,outlier_count
0,age,31.7500,58.0000,26.250,-7.6250,97.3750,1
1,purchase_count,10.7500,24.5000,13.750,-9.8750,45.1250,0
2,avg_order_value,108.1375,324.1075,215.970,-215.8175,648.0625,0
3,total_spending,1167.0350,4692.1500,3525.115,-4120.6375,9979.8225,5
4,last_purchase_days,134.2500,273.7500,139.500,-75.0000,483.0000,0
5,returned_items,2.0000,7.0000,5.000,-5.5000,14.5000,0
6,satisfaction_score,2.0000,4.0000,2.000,-1.0000,7.0000,0

In [56]:
df[df['age'] > 97.375]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
9,1010,Arash,F,145,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1

In [57]:
df[df['total_spending'] > 9979.8225][[
    'customer_id',
    'first_name',
    'purchase_count',
    'avg_order_value',
    'total_spending',
    'membership_tier',
    'last_purchase_days'
]]

,customer_id,first_name,purchase_count,avg_order_value,total_spending,membership_tier,last_purchase_days
8,1009,Kimia,34,341.63,11615.42,Silver,232
11,1012,Arash,27,434.50,11731.50,Gold,224
29,1030,Sina,26,156.89,25000.00,VIP,340
43,1044,Mina,33,434.98,14354.34,Gold,165
56,1057,Maryam,31,436.54,13532.74,Bronze,82

In [58]:
df[df['total_spending'] > 9979.8225][[
    'customer_id',
    'purchase_count',
    'avg_order_value',
    'total_spending'
]].assign(
    calculated_spending=lambda x:
    x['purchase_count'] * x['avg_order_value']
)

,customer_id,purchase_count,avg_order_value,total_spending,calculated_spending
8,1009,34,341.63,11615.42,11615.42
11,1012,27,434.50,11731.50,11731.50
29,1030,26,156.89,25000.00,4079.14
43,1044,33,434.98,14354.34,14354.34
56,1057,31,436.54,13532.74,13532.74

In [59]:
df.loc[df['customer_id'] == 1010, 'age'] = 45

In [60]:
df.loc[df['customer_id'] == 1030, 'total_spending'] = 4079.14

In [61]:
df[df['customer_id'].isin([1010, 1030])][[
    'customer_id',
    'first_name',
    'age',
    'purchase_count',
    'avg_order_value',
    'total_spending'
]]

,customer_id,first_name,age,purchase_count,avg_order_value,total_spending
9,1010,Arash,45,19,381.13,7241.47
29,1030,Sina,60,26,156.89,4079.14

In [62]:
df[df['returned_items'] > df['purchase_count']][[
    'customer_id',
    'first_name',
    'purchase_count',
    'returned_items',
    'membership_tier',
    'satisfaction_score'
]]

,customer_id,first_name,purchase_count,returned_items,membership_tier,satisfaction_score
7,1008,Reza,3,8,VIP,1
14,1015,Kimia,3,8,Gold,4
23,1024,Sina,0,2,Gold,1
28,1029,Ali,2,4,Gold,5
36,1037,Zahra,1,7,Gold,2
55,1056,Kimia,1,4,Silver,2

In [63]:
df[df['purchase_count'] > 0].assign(
    return_ratio=lambda x: x['returned_items'] / x['purchase_count']
)[['purchase_count', 'returned_items', 'return_ratio']].describe()

       purchase_count  returned_items  return_ratio
count       59.000000       59.000000     59.000000
mean        17.677966        4.220339      0.574332
std          9.974866        2.691415      1.114539
min          1.000000        0.000000      0.000000
25%         11.000000        2.000000      0.087596
50%         17.000000        4.000000      0.266667
75%         25.000000        7.000000      0.472222
max         35.000000        8.000000      7.000000

In [64]:
df.loc[df['returned_items'] > df['purchase_count'], 'returned_items'] = (
    df.loc[df['returned_items'] > df['purchase_count'], 'purchase_count']
)

In [65]:
df[df['returned_items'] > df['purchase_count']]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [66]:
df['calculated_spending'] = (
    df['purchase_count'] * df['avg_order_value']
)

In [67]:
df[df['total_spending'] != df['calculated_spending']][[
    'customer_id',
    'purchase_count',
    'avg_order_value',
    'total_spending',
    'calculated_spending'
]]

,customer_id,purchase_count,avg_order_value,total_spending,calculated_spending
1,1002,12,326.47,3917.64,3917.64
4,1005,23,169.54,3899.42,3899.42
6,1007,29,77.15,2237.35,2237.35
17,1018,18,109.70,1974.60,1974.60
29,1030,26,156.89,4079.14,4079.14
30,1031,18,106.43,1915.74,1915.74
32,1033,24,230.05,5521.20,5521.20
35,1036,9,115.60,1040.40,1040.40
45,1046,15,328.23,4923.45,4923.45
52,1053,18,322.53,5805.54,5805.54
58,1059,31,287.05,8898.55,8898.55
59,1060,10,150.18,1501.80,1501.80

In [68]:
import numpy as np

In [69]:

np.isclose(
    df['total_spending'],
    df['calculated_spending'],
    atol=0.01
).all()

np.True_

In [70]:
df.drop(columns=['calculated_spending'], inplace=True)

In [71]:
df.isnull().sum().sum()

np.int64(0)

In [72]:
df.duplicated().sum()

np.int64(0)

In [73]:
df[(df['age'] < 18) | (df['age'] > 100)]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [74]:
df[df['purchase_count'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [75]:
df[df['returned_items'] > df['purchase_count']]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [76]:
df[(df['satisfaction_score'] < 1) | (df['satisfaction_score'] > 5)]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [77]:
df[(df['avg_order_value'] < 0) | (df['total_spending'] < 0)]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [78]:
df[df['last_purchase_days'] < 0]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [79]:
df['signup_date'].dtype

dtype('<M8[us]')

In [80]:
df.drop(columns=['calculated_spending'], errors='ignore', inplace=True)

In [81]:
df.to_excel('cleaned_dataset.xlsx', index=False)

In [82]:
import os
print(os.path.abspath('.'))

d:\آموزشی\python\data cleaning