In [1]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_excel("First Dataset.xlsx")
df

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1057,Maryam,M,58.0,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4
57,1058,Amir,F,47.0,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2
58,1059,Ali,F,57.0,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5
59,1060,Ali,M,63.0,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         61 non-null     int64
 1   first_name          61 non-null     str
 2   gender              61 non-null     str
 3   age                 60 non-null     float64
 4   city                61 non-null     str
 5   province            61 non-null     str
 6   signup_date         61 non-null     str
 7   membership_tier     61 non-null     str
 8   purchase_count      61 non-null     int64
 9   avg_order_value     61 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  61 non-null     int64
 12  payment_method      61 non-null     str
 13  device              61 non-null     str
 14  discount_used       61 non-null     str
 15  returned_items      61 non-null     int64
 16  satisfaction_score  61 non-null     int64
dtypes: float64(3), int64(5), str(9)
memory usage: 8.2 KB

In [4]:
df.columns

Index(['customer_id', 'first_name', 'gender', 'age', 'city', 'province',
       'signup_date', 'membership_tier', 'purchase_count', 'avg_order_value',
       'total_spending', 'last_purchase_days', 'payment_method', 'device',
       'discount_used', 'returned_items', 'satisfaction_score'],
      dtype='str')

In [5]:
df.describe()

,customer_id,age,purchase_count,avg_order_value,total_spending,last_purchase_days,returned_items,satisfaction_score
count,61.000000,60.000000,61.000000,61.000000,60.000000,61.000000,61.000000,61.00000
mean,1030.229508,45.200000,17.606557,211.435738,3749.667333,196.934426,4.196721,3.00000
std,17.446483,19.167239,10.214824,130.113726,4262.248522,97.892436,2.663454,1.42595
min,1001.000000,19.000000,0.000000,27.630000,0.000000,3.000000,0.000000,1.00000
25%,1015.000000,31.750000,11.000000,108.190000,1167.035000,132.000000,2.000000,2.00000
50%,1030.000000,45.000000,17.000000,161.330000,2188.865000,201.000000,4.000000,3.00000
75%,1045.000000,58.000000,26.000000,323.320000,4692.150000,273.000000,7.000000,4.00000
max,1060.000000,145.000000,35.000000,449.810000,25000.000000,365.000000,8.000000,5.00000

In [6]:
df.nunique()

customer_id           60
first_name            12
gender                 2
age                   34
city                   8
province               8
signup_date           58
membership_tier        4
purchase_count        30
avg_order_value       60
total_spending        59
last_purchase_days    54
payment_method         3
device                 3
discount_used          2
returned_items         9
satisfaction_score     5
dtype: int64

In [7]:
df.isna().sum()

customer_id           0
first_name            0
gender                0
age                   1
city                  0
province              0
signup_date           0
membership_tier       0
purchase_count        0
avg_order_value       0
total_spending        1
last_purchase_days    0
payment_method        0
device                0
discount_used         0
returned_items        0
satisfaction_score    0
dtype: int64

In [8]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
56    False
57    False
58    False
59    False
60     True
Length: 61, dtype: bool

In [9]:
df[df.duplicated()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [10]:
df[df.customer_id==1014] # dup Row

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
60,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4

In [11]:
df = df.drop_duplicates() #removing dup

In [12]:
df

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
0,1001,Reza,F,19.0,Karaj,Alborz,2025-02-19,VIP,17,121.53,2066.01,16,Card,Android,Yes,3,5
1,1002,Sina,M,53.0,Tehran,Tehran,2022-08-19,Gold,12,326.47,3917.64,3,Card,Web,No,5,3
2,1003,Parsa,F,31.0,Shiraz,Fars,2023-06-20,Gold,21,59.46,1248.66,22,Online Wallet,iPhone,Yes,6,1
3,1004,Sina,F,58.0,Mashhad,Khorasan,2021-11-08,Gold,23,266.15,6121.45,40,Card,Android,No,4,4
4,1005,Kimia,M,28.0,Isfahan,Isfahan,2021-10-21,Silver,23,169.54,3899.42,273,Online Wallet,Android,Yes,7,4
5,1006,Amir,F,58.0,Mashhad,Khorasan,2022-01-26,Gold,35,110.53,3868.55,205,Cash,Android,Yes,5,2
6,1007,Reza,F,43.0,Rasht,Gilan,2025-09-09,VIP,29,77.15,2237.35,298,Cash,iPhone,Yes,2,5
7,1008,Reza,F,23.0,Rasht,Gilan,2024-10-03,VIP,3,389.58,1168.74,195,Online Wallet,iPhone,No,8,1
8,1009,Kimia,M,61.0,Karaj,Alborz,2021-05-14,Silver,34,341.63,11615.42,232,Card,Web,No,8,2
9,1010,Arash,F,145.0,Karaj,Alborz,2022-06-25,Silver,19,381.13,7241.47,276,Online Wallet,Android,No,7,1
10,1011,Neda,F,41.0,Karaj,Alborz,2021-12-16,Bronze,19,119.16,2264.04,272,Card,Android,No,8,2
11,1012,Arash,F,51.0,Mashhad,Khorasan,2023-07-22,Gold,27,434.50,11731.50,224,Online Wallet,iPhone,Yes,3,2
12,1013,Neda,F,39.0,Karaj,Alborz,2021-02-23,Bronze,1,270.91,270.91,117,Card,Android,No,1,5
13,1014,Reza,M,35.0,Tabriz,East Azerbaijan,2022-08-26,VIP,31,108.19,3353.89,97,Card,Android,No,5,4
14,1015,Kimia,F,47.0,Ahvaz,Khuzestan,2021-07-24,Gold,3,307.91,923.73,55,Card,Android,Yes,8,4
15,1016,Neda,F,45.0,Shiraz,Fars,2024-09-04,Bronze,11,136.17,1497.87,333,Online Wallet,Android,Yes,3,2
16,1017,Parsa,F,49.0,Ahvaz,Khuzestan,2022-07-01,VIP,30,107.98,3239.40,135,Cash,iPhone,No,8,4
17,1018,Ali,F,30.0,Shiraz,Fars,2023-01-02,VIP,18,109.70,1974.60,257,Online Wallet,Android,Yes,8,1
18,1019,Neda,M,22.0,Shiraz,Fars,2021-10-08,Bronze,4,308.72,1234.88,317,Card,iPhone,No,4,2
19,1020,Kimia,M,NaN,Isfahan,Isfahan,2024-06-25,Bronze,16,187.17,2994.72,4,Cash,Web,Yes,1,5
20,1021,Amir,F,50.0,Tabriz,East Azerbaijan,2022-06-10,Silver,16,72.62,1161.92,224,Online Wallet,Web,No,8,1
21,1022,Reza,M,60.0,Mashhad,Khorasan,2021-02-24,Silver,6,423.43,2540.58,139,Cash,Web,Yes,5,2
22,1023,Ali,F,50.0,Mashhad,Khorasan,2024-05-02,Bronze,31,124.24,3851.44,170,Card,Web,No,2,4
23,1024,Sina,F,53.0,Ahvaz,Khuzestan,2025-01-27,Gold,0,63.67,0.00,298,Online Wallet,Android,No,2,1
24,1025,Neda,F,41.0,Mashhad,Khorasan,2021-06-25,VIP,2,406.03,812.06,317,Online Wallet,Android,Yes,2,2
25,1026,Amir,M,19.0,Ahvaz,Khuzestan,2022-05-06,Bronze,11,335.41,3689.51,195,Card,iPhone,Yes,3,4
26,1027,Kimia,F,37.0,Isfahan,Isfahan,2024-06-09,Bronze,14,111.97,1567.58,142,Cash,Web,No,8,3
27,1028,Mina,F,25.0,Tehran,Tehran,2021-10-14,Gold,16,92.68,1482.88,160,Cash,Web,Yes,6,5
28,1029,Ali,F,34.0,Tabriz,East Azerbaijan,2023-07-03,Gold,2,323.32,646.64,319,Cash,Web,Yes,4,5
29,1030,Sina,M,60.0,Mashhad,Khorasan,2025-03-07,VIP,26,156.89,25000.00,340,Cash,Web,Yes,4,4
30,1031,Zahra,M,37.0,Tehran,Tehran,2024-08-15,Silver,18,106.43,1915.74,261,Cash,Web,Yes,1,3
31,1032,Neda,F,23.0,Isfahan,Isfahan,2022-01-02,Silver,15,307.67,4615.05,243,Online Wallet,Android,No,6,5
32,1033,Neda,F,63.0,Tabriz,East Azerbaijan,2021-02-25,VIP,24,230.05,5521.20,112,Card,Web,No,0,5
33,1034,Maryam,M,25.0,Tabriz,East Azerbaijan,2024-10-27,VIP,29,73.00,2117.00,280,Cash,Android,No,7,3
34,1035,Arash,M,58.0,Tabriz,East Azerbaijan,2022-05-15,Bronze,17,348.13,5918.21,365,Cash,Android,No,5,3
35,1036,Sina,F,26.0,Karaj,Alborz,2022-02-14,VIP,9,115.60,1040.40,169,Online Wallet,iPhone,No,0,2
36,1037,Zahra,M,42.0,Ahvaz,Khuzestan,2024-01-12,Gold,1,387.68,387.68,199,Cash,Web,Yes,7,2
37,1038,Amir,M,45.0,Mashhad,Khorasan,2022-08-05,Bronze,31,27.63,856.53,201,Online Wallet,Web,Yes,1,4
38,1039,Parsa,M,47.0,Shiraz,Fars,2022-08-11,Gold,11,36.87,405.57,194,Cash,iPhone,No,1,4
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2
40,1041,Neda,M,60.0,Rasht,Gilan,2023-06-06,Bronze,7,260.33,1822.31,83,Cash,Android,Yes,4,5
41,1042,Sina,F,43.0,Ahvaz,Khuzestan,2021-12-25,Gold,12,48.06,576.72,350,Online Wallet,Android,Yes,5,5
42,1043,Kimia,M,60.0,Ahvaz,Khuzestan,2021-07-27,VIP,23,45.00,1035.00,54,Cash,iPhone,No,2,4
43,1044,Mina,M,64.0,Shiraz,Fars,2024-07-27,Gold,33,434.98,14354.34,165,Card,Android,No,7,2
44,1045,Maryam,M,54.0,Rasht,Gilan,2022-08-07,Gold,24,161.33,3871.92,132,Cash,iPhone,No,8,1
45,1046,Maryam,F,23.0,Tabriz,East Azerbaijan,2024-11-23,VIP,15,328.23,4923.45,229,Card,Android,No,3,4
46,1047,Arash,M,37.0,Tabriz,East Azerbaijan,2024-12-18,Gold,23,220.87,5080.01,180,Online Wallet,iPhone,No,4,3
47,1048,Sina,F,25.0,Tabriz,East Azerbaijan,2022-04-24,VIP,12,152.26,1827.12,141,Online Wallet,Web,No,1,2
48,1049,Ali,F,32.0,Mashhad,Khorasan,2023-01-02,Gold,23,93.06,2140.38,357,Card,Web,No,1,1
49,1050,Reza,F,48.0,Mashhad,Khorasan,2023-08-04,Bronze,30,206.60,6198.00,205,Cash,Android,Yes,2,2
50,1051,Parsa,F,23.0,Mashhad,Khorasan,2025-07-15,VIP,15,66.53,997.95,152,Online Wallet,iPhone,No,0,5
51,1052,Sara,F,31.0,Karaj,Alborz,2022-03-18,Bronze,13,130.12,1691.56,80,Card,iPhone,No,7,3
52,1053,Sina,M,32.0,Tehran,Tehran,2021-11-08,Gold,18,322.53,5805.54,320,Online Wallet,Web,Yes,6,1
53,1054,Reza,F,59.0,Tabriz,East Azerbaijan,2021-03-26,Gold,9,410.16,3691.44,304,Online Wallet,Web,No,7,1
54,1055,Mina,M,62.0,Rasht,Gilan,2024-02-20,Bronze,19,319.38,6068.22,221,Online Wallet,iPhone,No,0,1
55,1056,Kimia,M,61.0,Tabriz,East Azerbaijan,2025-01-25,Silver,1,449.81,449.81,240,Online Wallet,Web,No,4,2
56,1057,Maryam,M,58.0,Ahvaz,Khuzestan,2024-06-11,Bronze,31,436.54,13532.74,82,Cash,iPhone,No,4,4
57,1058,Amir,F,47.0,Tehran,Tehran,2024-09-27,Bronze,5,151.81,759.05,336,Online Wallet,iPhone,No,0,2
58,1059,Ali,F,57.0,Isfahan,Isfahan,2023-09-05,Gold,31,287.05,8898.55,224,Online Wallet,iPhone,Yes,0,5
59,1060,Ali,M,63.0,Tabriz,East Azerbaijan,2021-04-27,Bronze,10,150.18,1501.80,236,Card,Web,Yes,7,3

In [13]:
df.dtypes

customer_id             int64
first_name                str
gender                    str
age                   float64
city                      str
province                  str
signup_date               str
membership_tier           str
purchase_count          int64
avg_order_value       float64
total_spending        float64
last_purchase_days      int64
payment_method            str
device                    str
discount_used             str
returned_items          int64
satisfaction_score      int64
dtype: object

In [14]:
df["signup_date"] = pd.to_datetime(df["signup_date"], errors="coerce")
df.dtypes

customer_id                    int64
first_name                       str
gender                           str
age                          float64
city                             str
province                         str
signup_date           datetime64[us]
membership_tier                  str
purchase_count                 int64
avg_order_value              float64
total_spending               float64
last_purchase_days             int64
payment_method                   str
device                           str
discount_used                    str
returned_items                 int64
satisfaction_score             int64
dtype: object

In [15]:
df.loc[df["age"] == 145, "age"] = 45
df["age"].mean() # new mean

np.float64(43.67796610169491)

In [16]:
df["age"].describe()

count    59.000000
mean     43.677966
std      14.065660
min      19.000000
25%      31.500000
50%      45.000000
75%      58.000000
max      65.000000
Name: age, dtype: float64

In [21]:
df[df["total_spending"].isnull()]

,customer_id,first_name,gender,age,city,province,signup_date,membership_tier,purchase_count,avg_order_value,total_spending,last_purchase_days,payment_method,device,discount_used,returned_items,satisfaction_score
39,1040,Amir,F,65.0,Tehran,Tehran,2021-11-02,Bronze,34,37.66,NaN,126,Card,Android,Yes,3,2

In [26]:
df.loc[df["total_spending"].isnull(), "total_spending"] = 34 * 37.66

In [27]:
df[df["total_spending"].isnull()]

Empty DataFrame
Columns: [customer_id, first_name, gender, age, city, province, signup_date, membership_tier, purchase_count, avg_order_value, total_spending, last_purchase_days, payment_method, device, discount_used, returned_items, satisfaction_score]
Index: []

In [30]:
df["age"] = df["age"].fillna(df["age"].median())

In [32]:
df["age"] = df["age"].astype(int)

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         60 non-null     int64
 1   first_name          60 non-null     str
 2   gender              60 non-null     str
 3   age                 60 non-null     int64
 4   city                60 non-null     str
 5   province            60 non-null     str
 6   signup_date         60 non-null     datetime64[us]
 7   membership_tier     60 non-null     str
 8   purchase_count      60 non-null     int64
 9   avg_order_value     60 non-null     float64
 10  total_spending      60 non-null     float64
 11  last_purchase_days  60 non-null     int64
 12  payment_method      60 non-null     str
 13  device              60 non-null     str
 14  discount_used       60 non-null     str
 15  returned_items      60 non-null     int64
 16  satisfaction_score  60 non-null     int64
dtypes: datetime64[us](1), float64(2), int64(6), str(8)
memory usage: 8.1 KB

In [34]:
df.to_excel("cleaned_dataset_sahandkhodayi.xlsx", index=False)